### ISSUE TITLE
Add support for bevy::reflect::Reflect

### ISSUE THREAD

**Issue by naomijub** [idanarye/bevy-yoleck#27]
Please add Bevy::reflect support for exposed field that can be managed from client side.
Maybe feature flag it

**Comment by idanarye** [comment]
What components need to be `Reflect` though? Yoleck defines quite a few:

The ones used for the core Yoleck functionality:

* `YoleckEditMarker`
* `YoleckManaged`
* `YoleckBelongsToLevel`
* `YoleckRawEntry`
* `YoleckSystemMarker`
* `YoleckKnobMarker`

Most of them are marker components, so I'm not sure how useful it is to have reflection on them. `YoleckRawEntry` and `YoleckManaged` are the exception, but they mostly contain semi-structured data and I'm not sure how well reflection would work for them.

Then there are the Vpeol components (the ones used for visually editing entities in 2D/3D worlds). Many of them are only useful in the editor itself, so I don't see a reason to add reflection to them:

* `VpeolDragPlane`
* `VpeolCameraState`
* `VpeolWillContainClickableChildren`
* `YoleckRouteClickTo` (despite the name, it belongs to Vpeol, not Yoleck. Probably should have named it `VpeolRouteClickTo`. Not sure why I missed that)
* (also `SelectionCueAnimation`, but this one is private and I really see no point in exposing it...)
* `Vpeol2dCameraControl`
* `Vpeol3dCameraControl`
* `Vpeol3dThirdAxisWithKnob`

Then there are the ones that contain data that actually affect the entities in the game:

* `Vpeol2dPosition`
* `Vpeol2dRotatation`
* `Vpeol2dScale`
* `Vpeol3dPosition`
* `Vpeol3dRotatation`
* `Vpeol3dScale`

But since Yoleck already provides a way to edit them (that's the whole point) - why do we need reflection?

**Comment by naomijub** [comment]
To what I'm working with, must haves would be:
- Vpeol2dPosition
- Vpeol2dRotatation
- Vpeol2dScale
- Vpeol3dPosition
- Vpeol3dRotatation
- Vpeol3dScale

However, nice to haves would be:
- VpeolDragPlane
- VpeolCameraState
- YoleckRouteClickTo/VpeolRouteClickTo
- Vpeol2dCameraControl
- Vpeol3dCameraControl

> But since Yoleck already provides a way to edit them (that's the whole point) - why do we need reflection?
We need a way to edit them outside the Yoleck Editor, we are only partially using Yoleck
